### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by amponce** [dstroot/react-instagram#1]
Hello!

I came across this project and love your implementation using netlify-lambda for caching API calls. 

I've been researching ways to reduce requests to stay within Instagram's TOS and I'm grateful to come across your project. 

**I'm trying to spin up the repo as a test for a project that I'm working on and I was wondering if you could tell me what variables I need to add to .env?** 

**Is there any additional setup that might help me get your project running locally?**

Also, where would I store the token after I auth with firebase? Amazing work!

**Comment by dstroot** [comment]
Well... there are no environment vars.  Interestingly Instagram's API has no validation!  The one thing I did not implement is a TTL on the cache.  If this was to be used in production the cache would be indefinite.
